name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Build Toolkit"
    runs-on: "ubuntu-latest"
    steps:

      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            LICENSE
            README.md
            package.json
            package-lock.json
            install.bat
            start.bat
            dist
            !dist/*.ts
            !dist/build/update.js
            !dist/build/update.js.map

  create-zip:
    name: "Create Zip File"
    needs: [build]
    runs-on: "ubuntu-latest"

    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build

      - run: mkdir modules

      - name: Create Zip
        run: zip -r prod-toolkit.zip LICENSE README.md package.json package-lock.json install.bat start.bat scripts/* dist/* modules/*

      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          name: prod-toolkit
          path: prod-toolkit.zip

  release:
    name: "Release"
    needs: create-zip
    runs-on: "ubuntu-latest"

    steps:
      - name: Download zip
        uses: actions/download-artifact@v2
        with:
          name: prod-toolkit

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            prod-toolkit.zip
